// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     TSTypesJenny
//     LatestMajorsOrXJenny
//
// Run 'make gen-cue' from repository root to regenerate.

export interface Test {
  anotherPerson: {
    name: {
      firstName: string;
      lastName: string;
    };
    address: {
      city: {
        name: {
          shortName: string;
          fullName: string;
        };
      };
    };
  };
  field1: string;
  person: {
    name: {
      firstName: string;
      lastName: string;
    };
    address: {
      city: {
        name: {
          shortName: string;
          fullName: string;
        };
      };
    };
  };
  type: string;
}
