// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     TSTypesJenny
//     LatestMajorsOrXJenny
//
// Run 'make gen-cue' from repository root to regenerate.

export interface Test {
  arrayVal: Record<string, Array<number>>;
  intVal: Record<string, number>;
  mapVal: Record<string, Record<string, string>>;
  stringVal: Record<string, string>;
  /**
   * Comments for a struct type
   */
  structType: {
    field1: string;
    field2: number;
  };
}
