// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     CRDTypesJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package crd

import (
	_ "embed"

	"github.com/grafana/grafana/pkg/kinds/test"
	"github.com/grafana/grafana/pkg/kindsys/k8ssys"
)

// The CRD YAML representation of the Test kind.
//
//go:embed test.crd.yml
var CRDYaml []byte

// Test is the Go CRD representation of a single Test object.
// It implements [runtime.Object], and is used in k8s scheme construction.
type Test struct {
	k8ssys.Base[test.Test]
}

// TestList is the Go CRD representation of a list Test objects.
// It implements [runtime.Object], and is used in k8s scheme construction.
type TestList struct {
	k8ssys.ListBase[test.Test]
}
