// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     CRDTypesJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package crd

import (
	_ "embed"

	"github.com/grafana/grafana/pkg/kinds/enum"
	"github.com/grafana/grafana/pkg/kindsys/k8ssys"
)

// The CRD YAML representation of the Enum kind.
//
//go:embed enum.crd.yml
var CRDYaml []byte

// Enum is the Go CRD representation of a single Enum object.
// It implements [runtime.Object], and is used in k8s scheme construction.
type Enum struct {
	k8ssys.Base[enum.Enum]
}

// EnumList is the Go CRD representation of a list Enum objects.
// It implements [runtime.Object], and is used in k8s scheme construction.
type EnumList struct {
	k8ssys.ListBase[enum.Enum]
}
