// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     TSVeneerIndexJenny
//
// Run 'make gen-cue' from repository root to regenerate.

// Raw generated types from Test kind.
export type { Test } from './raw/test/x/test_types.gen';
