// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     GoTypesJenny
//     LatestJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package test

// Test defines model for test.
type Test struct {
	ArrayVal map[string][]int64 `json:"arrayVal"`
	IntVal   map[string]int64   `json:"intVal"`
	MapVal   map[string]struct {
		AdditionalProperties map[string]string `json:"-"`
	} `json:"mapVal"`
	StringVal map[string]string `json:"stringVal"`

	// Comments for a struct type
	StructType struct {
		Field1 string `json:"field1"`
		Field2 int64  `json:"field2"`
	} `json:"structType"`
}
