// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     GoTypesJenny
//     LatestJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package test

// Person defines model for Person.
type Person struct {
	Address struct {
		City struct {
			Name struct {
				FullName  string `json:"fullName"`
				ShortName string `json:"shortName"`
			} `json:"name"`
		} `json:"city"`
	} `json:"address"`
	Name struct {
		FirstName string `json:"firstName"`
		LastName  string `json:"lastName"`
	} `json:"name"`
}

// Test defines model for Test.
type Test struct {
	AnotherPerson Person `json:"anotherPerson"`
	Field1        string `json:"field1"`
	Person        Person `json:"person"`
	Type          string `json:"type"`
}
